# Generated by Django 4.2.20 on 2025-03-13 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('home_address', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('favorite_pick_up_point', models.CharField(blank=True, max_length=200)),
                ('companies', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_method_expiry', models.CharField(blank=True, max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
